//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoolDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.BloodDonations = new HashSet<BloodDonation>();
            this.BloodDonation_Detail = new HashSet<BloodDonation_Detail>();
            this.Ketquakhams = new HashSet<Ketquakham>();
        }

        public int BatchID { get; set; }
        [Display(Name = "Tên đợt hiến")]
        public string BatchName { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Thời gian dự kiến hiến")]
        public Nullable<System.DateTime> Thoigianhien { get; set; }
        [Display(Name = "Người tạo đợt hiến máu")]
        public string Nguoitaohien { get; set; }
        public Nullable<int> StatusDothien { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        [Display(Name = "Thời gian thêm đợt hiến hiến")]
        public Nullable<System.DateTime> Thoigianthemluothien { get; set; }
        [Display(Name = "Thời gian bắt đầu hiến")]
        [DataType(DataType.Time), DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Thoigianbatdau { get; set; }
        [Display(Name = "Thời gian kết thúc hiến")]
        [DataType(DataType.Time), DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Thoigianketthuc { get; set; }
        [Display(Name = "Số lượng dự kiến")]
        public Nullable<int> Soluongdukien { get; set; }
        public Nullable<int> Soluongdem { get; set; }
        public Nullable<int> idLocaltion { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodDonation> BloodDonations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodDonation_Detail> BloodDonation_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ketquakham> Ketquakhams { get; set; }
    }
}
