//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoolDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodDonation_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BloodDonation_Detail()
        {
            this.Khamsanlocs = new HashSet<Khamsanloc>();
        }
    
        public int Blood_DetalID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> BloodID { get; set; }
        public Nullable<System.DateTime> Thoigianhien { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> songaycothehienlai { get; set; }
        public string CMND { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual BloodDonation BloodDonation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khamsanloc> Khamsanlocs { get; set; }
    }
}
