//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoolDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BloodDonation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BloodDonation()
        {
            this.BloodDonation_Detail = new HashSet<BloodDonation_Detail>();
            this.Khamsanlocs = new HashSet<Khamsanloc>();
            this.Logs = new HashSet<Log>();
        }

        public int BloodID { get; set; }
        [Display(Name = "Họ và Tên")]
        [Required(ErrorMessage = "Vui lòng nhập Họ và Tên")]
        public string Hovaten { get; set; }
        [Display(Name = "Ngày sinh")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Vui lòng nhập ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [Display(Name = "Số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Số điện thoại không hợp lệ")]
        public string Phone { get; set; }
        [Display(Name = "Địa Chỉ ")]
        public string DiaChi { get; set; }
        [Display(Name = "Email ")]

        public string Email { get; set; }
        public Nullable<int> BatchID { get; set; }
        [Display(Name = "Nhóm máu ")]
        [Required(ErrorMessage = "Vui lòng nhập nhóm máu ")]
        public string NhomMau { get; set; }
        [Display(Name = "Số lần hiến máu")]
        public Nullable<int> Solanhienmau { get; set; }
        [MinLength(12, ErrorMessage = "Số CCCD hoặc CMNN phải đủ 12 số")]
        [Display(Name = "Số CMND/CCCD")]
        [Required(ErrorMessage = "Vui lòng nhập số CMND ")]
        public string CMND { get; set; }
        public int IdUser { get; set; }
        [Display(Name = "Giới tính ")]
        [Required(ErrorMessage = "Vui lòng nhập giới tính ")]
        public Nullable<int> gioitinh { get; set; }
        public Nullable<int> IsActive { get; set; }
        [Display(Name = "Căn cước công dân")]
        public string CCCD { get; set; }
        [Display(Name = "Đơn vị công tác")]
        public string Donvicongtac { get; set; }
        public Nullable<int> IDPhuong { get; set; }
        public Nullable<int> IDQuan { get; set; }
        public Nullable<int> IDTinh { get; set; }
        public Nullable<int> IDQuocGia { get; set; }
        public string Nest { get; set; }
        public string sonha { get; set; }
        public string duong { get; set; }
        public Nullable<bool> truocdayquividatunghienmauchuacau1 { get; set; }
        public Nullable<bool> tamthankinhcau2 { get; set; }
        public Nullable<bool> sutcan4kgcau3 { get; set; }
        public Nullable<bool> noihachkeodaicau4 { get; set; }
        public Nullable<bool> phauthuatcau5 { get; set; }
        public Nullable<bool> xamminhxolocau6 { get; set; }
        public Nullable<bool> duoctruyenmaucau7 { get; set; }
        public Nullable<bool> sudungmatuycau8 { get; set; }
        public Nullable<bool> quanhetinhduccau9 { get; set; }
        public Nullable<bool> quanhetinhducvoinguoidonggioicau10 { get; set; }
        public Nullable<bool> tiemvacxinphongbenhcau11 { get; set; }
        public Nullable<bool> songtrongvungcodichluuhanhcau12 { get; set; }
        public Nullable<bool> bicumhonhucdausotcau13 { get; set; }
        public Nullable<bool> dungthuockhangsinhcau14 { get; set; }
        public Nullable<bool> denkhamsuckhoelamxetnghiemchuarangcau15 { get; set; }
        public Nullable<bool> quivihienladoituongtantatcau16 { get; set; }
        public Nullable<bool> chihiendangnuoiconduoi12thangtuoicau17 { get; set; }
        public Nullable<bool> chidatungcothaihoacsinhconchuacau18 { get; set; }
        public Nullable<System.DateTime> ngayhienmaugannhat { get; set; }
    
        public virtual Batch Batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodDonation_Detail> BloodDonation_Detail { get; set; }
        public virtual Tinh Tinh { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khamsanloc> Khamsanlocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}
