//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoolDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ketquakham
    {
        public int ResultsScreeningID { get; set; }
        public Nullable<int> KhamsanlocID { get; set; }
        public Nullable<int> BloodID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> Blood_DetalID { get; set; }
        public Nullable<System.DateTime> Ngaylaymau { get; set; }
        public string Phanung { get; set; }
        public string Matuimau1 { get; set; }
        public string MatuiPooltieucau { get; set; }
        public string Maday { get; set; }
        public Nullable<int> Luongmau { get; set; }
        public Nullable<int> Thetich { get; set; }
        public Nullable<int> Xutri { get; set; }
        public string MatuiPoolTualanh { get; set; }
        public string MatuiPoolHuyettuong { get; set; }
        public string KTVlaymau { get; set; }
        public string HBSAG { get; set; }
        public string AntiHCV { get; set; }
        public string AntiHIV { get; set; }
        public string AntiHBV { get; set; }
        public string NATHCV { get; set; }
        public string NATHIV { get; set; }
        public string NATHBV { get; set; }
        public string SLKTBT { get; set; }
        public string Combstructiep { get; set; }
        public string username { get; set; }
        public Nullable<int> songaycothehienlai { get; set; }
        public Nullable<System.DateTime> thoigiantaoketqua { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual BloodDonation BloodDonation { get; set; }
        public virtual BloodDonation_Detail BloodDonation_Detail { get; set; }
        public virtual Khamsanloc Khamsanloc { get; set; }
    }
}
