//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoolDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> Log_Time { get; set; }
        public Nullable<int> BloodID { get; set; }
        public string action { get; set; }
        public string nguoithaotac { get; set; }
    
        public virtual BloodDonation BloodDonation { get; set; }
    }
}
