//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoolDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quan
    {
        public int IDQuan { get; set; }
        public Nullable<int> IDTinh { get; set; }
        public string MaQuan { get; set; }
        public string TenQ { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
