//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoolDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuocGia
    {
        public int IDQuocGia { get; set; }
        public string MaQG { get; set; }
        public string TenQG { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
